---

- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - name: enable repos
    template:
      src: ./open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: setup app 
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: app}

- name: setup frontend 
  hosts: frontends
  become: yes
  gather_facts: false
  roles:
    - {name: frontend}

- name: setup db
  hosts: appdbs
  become: yes
  gather_facts: false
  roles:
    - {name: db}

