---

- name: install postgres
  yum:
    name: postgresql-server
    state: latest

- name: Check if PostgreSQL database is initialized.
  stat:
    path: /var/lib/pgsql/data/PG_VERSION
  register: pgdata_version

- name: Ensure PostgreSQL database is initialized.
  command: /usr/bin/postgresql-setup initdb
  command: /usr/sbin/chkconfig postgresql on
  when: not pgdata_version.stat.exists

- name: restart postgres
  service:
    name: postgresql
    state: restarted


  
